version: "3.8"
services: 
  mongodb:
    image: "mongo"
    volumes: 
      - mongo-data:/data/db
    env_file: 
      - ./config/development.env
  frontend:
    build: ./client
    ports: 
      - "3000:3000"
    volumes: 
      - ./client/src:/client/src
  backend:
    build: ./server
    ports: 
      - "5000:5000"
    volumes: 
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    env_file: 
      - ./config/development.env
volumes: 
  mongo-data:
  
